#!/bin/bash
[ -d build ] || mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="../" ..
echo -e "\n\n=====================================\nCompiling the program...\n=====================================\n"
cmake --build .
[ -d ../bin ] || mkdir ../bin
cmake --install .
cd ..
echo -e "\n\n=====================================\nRunning the program...\n=====================================\n"
bin/demo
