#!/bin/bash
cd build
cmake -DCMAKE_INSTALL_PREFIX="../" ..
echo -e "\n\n=====================================\nCompiling the program...\n=====================================\n"
cmake --build .
cmake --install .
cd ..
echo -e "\n\n=====================================\nRunning the program...\n=====================================\n"
bin/demo
