#!/bin/bash

cd $HOME

# Check if there is an argument with the name of the lab.
# If not, exit.
if [[ -z $1 ]]
then
  printf "Debes proporcionar el nombre de la práctica que quieres empezar.\n"
  printf "Por ejemplo: startlab lab10603\n"
  printf "Consulta el nombre de la práctica en Schoology.\n"
  [[ $0 = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

[[ $USER =~ -(.*) ]]
username=${BASH_REMATCH[1]}

# Check if user.name and user.email are configured.
# If not, set them.
if [[ -z $(git config --global user.name) ]]
then
  git config --global user.name "$username"
fi
if [[ -z $(git config --global user.email) ]]
then
  git config --global user.email "$username@gototicmail.com"
fi

# Check if there is already a folder with the lab's name,
# and warn the user of data lost in case of proceeding.
if [ -d $1 ]
then
  echo "Ya tienes una carpeta llamada $1. Si continúas, perderás todo su contenido." 
  read -p "¿Estás seguro de que quieres continuar (S/n)? " -n 1 -r
  if [[ ! $REPLY =~ ^[Ss]$ ]]
  then
    [[ $0 = "$BASH_SOURCE" ]] && exit 1 || return 1
  fi
  rm -rf $1
fi

# Clone the remote repo.
printf "\n"
git clone https://gitlab.gototic.com/root/$1.git
cd $1
git remote remove origin

# Perform login if not previously done.
if [ ! -f $HOME/.gitlabctl.yaml ]
then
  gitlabctl login -H https://gitlab.gototic.com -u $username
fi

# Create a new remote project and add root as a member.
if [[ -z $(gitlabctl get projects | grep $username/$1) ]]
then
  gitlabctl new project $1
  gitlabctl new member root --from-project $username/$1 --access-level 40
fi

# Add new remote project as origin for local repo.
git remote add origin https://gitlab.gototic.com/$username/$1.git
git push -u origin main

printf "\nYa tienes la práctica $1 descargada y puedes empezar a trabajar en ella.\n"
printf "En Visual Studio Code, selecciona la opción 'Open folder', y elige la carpeta $HOME/$1\n"
printf "\n"
printf "Para ejecutar el programa, en este terminal, escribe 'runprogram', o 'rp'.\n"
printf "Para probar si el programa funciona como debería, escribe 'testprogram', o 'tp'.\n"
printf "Cuando el programa funcione correctamente, ejectura 'submitlab' en la consola para entregarlo.\n"