#!/bin/bash

[[ $USER =~ -(.*) ]]
username=${BASH_REMATCH[1]}
if [ ! -z $1 ]
then
  cd $HOME/$1
fi
if [! git rev-parse --is-inside-work-tree ]
then
  printf "La carpeta seleccionada no es una práctica. Si no indicaste el nombre de la práctica al ejecutar el commando 'submit', vuelve a ejecutarlo indicando el nombre de la práctica que quieres entregar. Por ejemplo: 'submitlab lab10602'\n"
  [[ $0 = "$BASH_SOURCE" ]] && exit 1 || return 1
fi
reponame=$(basename $(git rev-parse --show-toplevel))
if [ -n "$(git status --porcelain)" ]
then
  git add .
  git commit -m "Submit lab"
fi
if [ $(git push) ]
then
  printf "Has entregado la práctica $reponame.\n"
  printf "Puedes ver el código entregado en https://gitlab.gototic.com/$username/$reponame.git"
else
  printf "Ha habido problemas al entregar la práctica $reponame.\n"
  printf "La práctica $reponame no ha sido entregada.\n"
  printf "Consulta con el profesor."
fi