#!/bin/bash

red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

[[ $USER =~ -(.*) ]]
username=${BASH_REMATCH[1]}
if [ ! -z $1 ]
then
  cd $HOME/$1
fi
if [[ ! $(git rev-parse --is-inside-work-tree) == *"true"* ]]
then
  printf "${red}La carpeta seleccionada no es una práctica${end}. Si no indicaste el nombre de la práctica al ejecutar el commando 'submit', vuelve a ejecutarlo indicando el nombre de la práctica que quieres entregar. Por ejemplo: 'submitlab lab10602'\n"
  [[ $0 = "$BASH_SOURCE" ]] && exit 1 || return 1
fi
reponame=$(basename $(git rev-parse --show-toplevel))
if [ -n "$(git status --porcelain)" ]
then
  git add .
  git commit -m "Submit lab"
fi
if [[ "$(git push --porcelain)" == *"Done"* ]]
then
  printf "\n${green}Has entregado la práctica $reponame.${end}\n"
  printf "Puedes ver el código entregado en https://gitlab.gototic.com/$username/$reponame.git\n"
else
  printf "\nHa habido problemas al entregar la práctica $reponame.\n"
  printf "${red}La práctica $reponame no ha sido entregada.${end}\n"
  printf "Consulta con el profesor.\n\n"
fi