#!/bin/bash

red=$'\e[1;31m'
grn=$'\e[1;32m'
yel=$'\e[1;33m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
end=$'\e[0m'

[[ $USER =~ -(.*) ]]
username=${BASH_REMATCH[1]}

# if argument given, cd into it. Otherwise, use current folder
if [ ! -z $1 ]
then
  if ! cd $HOME/$1
  then
    printf "\n\n${red}ERROR: la existe ningún repositorio local llamado $1.\n\n${end}"
    printf "${yel}Revisa si has escrito bien el nombre.\n"
    [[ $0 = "$BASH_SOURCE" ]] && exit 1 || return 1
  fi
fi

# Check if inside a repo
if [[ ! $(git rev-parse --is-inside-work-tree) == *"true"* ]]
then
  printf "\n\n${red}ERROR: La carpeta seleccionada no es una práctica${end}.\n\n"
  printf "${yel}Si no indicaste el nombre de la práctica al ejecutar el commando 'submit', vuelve a ejecutarlo indicando el nombre de la práctica que quieres entregar. Por ejemplo: 'submitlab lab10602'\n\n${end}"
  [[ $0 = "$BASH_SOURCE" ]] && exit 1 || return 1
fi

reponame=$(basename $(git rev-parse --show-toplevel))

# Check if repo is up-to-date
if [ -n "$(git status --porcelain)" ]
then
  git add .
  git commit -m "Submit lab"
fi

# Perform a git push and check if it's successful
if [[ "$(git push --porcelain)" == *"Done"* ]]
then
  printf "\n${grn}Has entregado la práctica $reponame.${end}\n\n"
  printf "${blu}Puedes ver el código entregado en https://gitlab.gototic.com/$username/$reponame.git\n${end}"
  printf "${blu}Puedes volver a entregarla ejecutando submitlab $reponame en el terminal.\n"
else
  printf "${red}ERROR: La práctica $reponame no ha sido entregada.${end}\n\n"
  printf "\n${yel}Ha habido problemas al entregar la práctica $reponame.\n"
  printf "\nAsegúrate de haber escrito bien tu usuario y contraseña de gitlab.\n"
fi