#!/bin/bash

[ -d build ] || mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="../" ..
echo -e "\n\n=====================================\nCompiling the program...\n=====================================\n"
cmake --build .
echo -e "\n\n=====================================\nRunning the tests...\n=====================================\n"
test/Test
cd ..
